// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

namespace TestCase1
{
    [TestFixture]
    public class TechLoansFinesTest
    {
        private IWebDriver driver;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;
        [SetUp]
        public void SetUp()
        {
            driver = new ChromeDriver();
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
        }
        [TearDown]
        protected void TearDown()
        {
            driver.Quit();
        }
        [Test]
        public void techLoansFines()
        {
            driver.Navigate().GoToUrl("https://lib.conestogac.on.ca/Tech-Loans-Help/fines");
            driver.Manage().Window.Size = new System.Drawing.Size(837, 754);
            driver.FindElement(By.LinkText("Fines")).Click();
            driver.Close();
        }
    }

}
