// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;


namespace TestCase2
{
    [TestFixture]
    public class TechResourcesTest
    {
        private IWebDriver driver;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;
        [SetUp]
        public void SetUp()
        {
            driver = new ChromeDriver();
            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
        }
        [TearDown]
        protected void TearDown()
        {
            driver.Quit();
        }
        [Test]
        public void techResources()
        {
            driver.Navigate().GoToUrl("https://lib.conestogac.on.ca/Tech-Loans-Help/fines");
            driver.Manage().Window.Size = new System.Drawing.Size(838, 754);
            driver.FindElement(By.CssSelector(".icon-bar:nth-child(4)")).Click();
            Thread.Sleep(500); // Add a 0.5 sec delay to let the nav bar load in high traffic
            driver.FindElement(By.XPath("/html/body/header/header/nav/div/div[2]/ul/li[1]/a")).Click();
            driver.FindElement(By.CssSelector(".col-xs-12:nth-child(2) .list-group-item:nth-child(2) > .h4")).Click();
            driver.Close();
        }
    }
}
